# This dataset config is for weekly pulls of the Weekly Hospital Respiratory
# Data (HRD) Metrics by Jurisdiction, National Healthcare Safety Network
# (NHSN) (Preliminary)

############################################################################

[properties]
# The name field is the only required field here. Though other
# files can be accessed in the datacat by key/name.

name = "nwss"
automate = false
transform_templates = ["{location for any sql applied to reference data}"]
# schemas = "{path file containing any dataframe schema definitions}"
type = "etl"

############################################################################

[source]
# These source fields are open to being changed based on the source type
# and api requirements. This example uses a Socrata data source
# which is common for CDC data sources.

domain = "1cdp.cdc.gov"
# with data coming from 1CDP, will need to figure out access, RID and tokens
# azure keyvault would be great, but env variables is an option for now

############################################################################

[extract]
# These are the details of where to store the raw extracted data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/stf/raw/nwss"

############################################################################

[load]
# These are the details of where to store the transformed and loaded data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/stf/transformed/nwss"

############################################################################

# Changelog
# ---------
# 2025-12-08: Initial version created by Phil Rogers
